"""Adding grupo and name to constancias.

Revision ID: ee31565fadf4
Revises: 86e13c6ba6e4
Create Date: 2023-02-15 01:01:13.725181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee31565fadf4'
down_revision = '86e13c6ba6e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constancias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
    #     batch_op.drop_table_comment(
    #     'constancias',
    #     existing_comment='Constancias solicitadas',
    #     schema=None
    # )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constancias', schema=None) as batch_op:
        batch_op.create_table_comment(
        'constancias',
        'Constancias solicitadas',
        existing_comment=None,
        schema=None
    )
        batch_op.drop_column('name')
        batch_op.drop_column('grupo')

    # ### end Alembic commands ###
